document:
  name: Specifiche Attuative del Nodo dei Pagamenti-SPC
  description: |
    Il presente documento denominato “Specifiche Attuative 
    del Nodo dei Pagamenti-SPC” rappresenta l’Allegato B alle 
    “Linee guida per l'effettuazione dei pagamenti a favore  	
    delle pubbliche amministrazioni e dei gestori di pubblici servizi” 
    e deve essere utilizzato in combinazione con il documento 
    "Specifiche attuative dei codici identificativi di versamento,
    riversamento e rendicontazione" 
    (Allegato A), nonché con le stesse Linee guida; 
    documenti ai quali si rimanda per tutte le voci e gli 
    argomenti non specificatamente qui indicati.    
  tags:
    - SANP
    - pagoPA
    - PA
    - AgID
